// src/routes/Footer.svelte
<footer class="py-16 text-center text-sm text-black dark:text-white/70">
  <p>hyrorre all rights reserved.</p>
  <p class="mt-2">
    <a
      href="https://github.com/hyrorre/infs"
      target="_blank"
      class="hover:text-black/70 hover:dark:text-white/50"
    >
      GitHub
    </a>
    <a href="https://x.com/hyrorre" target="_blank" class="ml-2 hover:text-black/70 hover:dark:text-white/50">
      Twitter
    </a>
  </p>
</footer>

// components/Footer.vue
<template>
  <footer class="py-16 text-center text-sm text-black dark:text-white/70">
    <p>hyrorre all rights reserved.</p>
    <p class="mt-2">
      <u-link to="https://github.com/hyrorre/Reflux-Cloud" target="_blank">GitHub</u-link>
      <u-link to="https://x.com/hyrorre" target="_blank" class="ml-2">Twitter</u-link>
    </p>
  </footer>
</template>
